import '@/styles/global.css';
import 'react-toastify/dist/ReactToastify.css';
import Footer from '@/components/layout/Footer';
import React, { Suspense } from 'react';
import { Inter } from 'next/font/google';
import localFont from 'next/font/local';
import LoadingHeader from '@/components/layout/header/LoadingHeader';
import Header from '@/components/layout/header/Header';
import { preloadSession } from '@/libs/session';
import { ToastContainer } from 'react-toastify';

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
};

const inter = Inter({
    subsets: ['latin'],
    weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});

const seven = localFont({
    src: [{ path: '../../public/fonts/seven/minecraft.ttf' }, { path: '../../public/fonts/seven/minecraft.woff' }],
    variable: '--font-seven'
});

const minecraft = localFont({
    src: '../../public/fonts/minecraft.ttf',
    variable: '--font-minecraft'
});

export default async function RootLayout({ children }: { children: React.ReactNode }) {
    preloadSession();

    return (
        <html lang="en">
            <head>
                <meta name="google-site-verification" content="Cfjkkj0GptctyosfkmnX3BO6kR2FX8sfieqs2eOsWo8" />
                <title>Hardel Labs</title>
            </head>
            <body
                className={[
                    'min-h-screen flex flex-col justify-between background-grid',
                    seven.variable,
                    minecraft.variable,
                    inter.className
                ].join(' ')}
            >
                <Suspense fallback={<LoadingHeader />}>
                    <Header />
                </Suspense>
                <ToastContainer position="bottom-right" theme="dark" />
                <main className={'min-h-[100dvh] flex flex-col mt-20'}>{children}</main>
                <Footer />
            </body>
        </html>
    );
}
