import '@/styles/global.css';
import Footer from '@/components/layout/Footer';
import React, { Suspense } from 'react';
import { Inter } from 'next/font/google';
import localFont from 'next/font/local';
import { getServerSession } from 'next-auth/next';
import SessionProvider from '@/components/layout/SessionProvider';
import LoadingHeader from '@/components/layout/header/LoadingHeader';
import Header from '@/components/layout/header/Header';

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
};

const inter = Inter({
    subsets: ['latin']
});

const seven = localFont({
    src: [{ path: '../../public/fonts/seven/minecraft.ttf' }, { path: '../../public/fonts/seven/minecraft.woff' }],
    variable: '--font-seven'
});

const minecraft = localFont({
    src: '../../public/fonts/minecraft.ttf',
    variable: '--font-minecraft'
});

export default async function RootLayout({ children }: { children: React.ReactNode }) {
    const session = await getServerSession();

    return (
        <html lang="en">
            <head>
                <meta name="google-site-verification" content="Cfjkkj0GptctyosfkmnX3BO6kR2FX8sfieqs2eOsWo8" />
                <title>Hardel Labs</title>
            </head>
            <body
                className={[
                    'min-h-screen flex flex-col justify-between background-grid',
                    seven.variable,
                    minecraft.variable,
                    inter.className
                ].join(' ')}
            >
                <SessionProvider session={session}>
                    <Suspense fallback={<LoadingHeader />}>
                        <Header />
                    </Suspense>
                    <main>{children}</main>
                    <Footer />
                </SessionProvider>
            </body>
        </html>
    );
}
